name: Lint and Format

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

          name: Golang Formatter

  formatting:
    name: Golang Formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Golang Formatter
        uses: sladyn98/auto-go-format@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
