name: Testing

on:
  workflow_call:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  tests:
    name: Testing
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: go test -v ./...

  freebsd:
    name: FreeBSD 14
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.22]
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          GO_VER=$(echo ${{ matrix.go}} | tr -d .)
          pkg install -y go$GO_VER

        run: |
          env
          freebsd-version
          go test -v
